# Generated by Django 5.1.3 on 2025-05-11 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('edad', models.PositiveIntegerField(verbose_name='Edad')),
                ('imc', models.FloatField(verbose_name='Índice de Masa Corporal')),
                ('actividad_fisica', models.FloatField(verbose_name='Nivel de actividad física semanal (horas)')),
                ('presion_arterial', models.IntegerField(verbose_name='Presión arterial sistólica')),
                ('antecedentes_familiares', models.BooleanField(choices=[(True, 'Sí'), (False, 'No')], verbose_name='Antecedentes familiares de diabetes')),
                ('glucosa_ayunas', models.FloatField(verbose_name='Nivel de glucosa en ayunas (mg/dL)')),
                ('riesgo_diabetes', models.BooleanField(blank=True, null=True, verbose_name='Riesgo de diabetes')),
                ('probabilidad_riesgo', models.FloatField(blank=True, null=True, verbose_name='Probabilidad de riesgo (%)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
            ],
            options={
                'verbose_name': 'Paciente',
                'verbose_name_plural': 'Pacientes',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
